"""
Configuration file for Multimodal Fashion Retrieval System
Auto-generated by setup_config.py
"""

# =============================================================================
# Supabase Configuration
# =============================================================================
SUPABASE_URL = "https://tfjlbyxssjxhuoblklxa.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmamxieXhzc2p4aHVvYmxrbHhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MjgzNjgsImV4cCI6MjA2NjMwNDM2OH0.dRjcgaI1v9nAasLEqAPPGZjWb6abucdmMTr8I9Z3iDI"

# =============================================================================
# GitHub Configuration
# =============================================================================
GITHUB_REPO_SLUG = "rahulsharma/multimodal-fashion-retrieval"
GITHUB_REPO_URL = f"https://github.com/{GITHUB_REPO_SLUG}"

# =============================================================================
# System Configuration
# =============================================================================

# CLIP Model Configuration
CLIP_MODEL = "ViT-B/32"
DEVICE = "auto"  # Will auto-detect: mps (Apple Silicon), cuda, or cpu

# FAISS Configuration
FAISS_INDEX_TYPE = "IndexFlatIP"  # Inner product for cosine similarity
FAISS_DIMENSION = 512  # CLIP ViT-B/32 embedding dimension

# Search Configuration
DEFAULT_TOP_K = 10
DEFAULT_ALPHA = 0.5  # Default image/text blending weight

# File Paths
DEFAULT_EMBEDDINGS_FILE = "embeddings.npy"
DEFAULT_PATHS_FILE = "index_paths.txt"

# Environment Variables
KMP_DUPLICATE_LIB_OK = "TRUE"  # Required for FAISS on macOS

# =============================================================================
# Validation Functions
# =============================================================================

def validate_config():
    """Validate that all required configuration is set"""
    issues = []
    
    if SUPABASE_URL == "https://your-project-id.supabase.co":
        issues.append("SUPABASE_URL not configured")
    
    if SUPABASE_KEY == "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...":
        issues.append("SUPABASE_KEY not configured")
    
    # Check if GitHub repo is still the default placeholder
    if GITHUB_REPO_SLUG == "your-username/multimodal-fashion-retrieval":
        issues.append("GITHUB_REPO_SLUG not configured")
    
    if issues:
        print("⚠️ Configuration issues found:")
        for issue in issues:
            print(f"   - {issue}")
        print("\nPlease update config.py with your actual values.")
        return False
    
    print("✅ Configuration validated successfully!")
    return True

if __name__ == "__main__":
    validate_config() 