name: CI

on: [push, pull_request]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: |
          pip install -r requirements.txt
          pip install -e .
          pytest -q
      - name: Build Docker image
        run: docker build -t mywardrobe:${{ github.sha }} -f infra/Dockerfile .
  # Add a deploy job here to push to Render or Railway if tests pass 